// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DisplaySensors.h"
#include "Commands/DrivetoWall.h"
#include "Commands/EmergencyStop.h"
#include "Commands/PushDisk.h"
#include "Commands/ShooterAdjustAngleDown.h"
#include "Commands/ShooterAdjustAngleUp.h"
#include "Commands/ShooterJoystickDrive.h"
#include "Commands/ShooterShoot.h"
#include "Commands/ShooterSpinUp.h"
#include "Commands/ShooterStop.h"
#include "Commands/TeleopDrive.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveJoystick = new Joystick(1);
	
	angleDown = new JoystickButton(driveJoystick, 3);
	angleDown->WhileHeld(new ShooterAdjustAngleDown());
	angle_Up = new JoystickButton(driveJoystick, 5);
	angle_Up->WhileHeld(new ShooterAdjustAngleUp());
	emergencyStopButton = new JoystickButton(driveJoystick, 12);
	emergencyStopButton->WhenPressed(new EmergencyStop());
	stopWheels = new JoystickButton(driveJoystick, 4);
	stopWheels->WhenPressed(new ShooterStop());
	wallDriveButton = new JoystickButton(driveJoystick, 6);
	wallDriveButton->WhenPressed(new DrivetoWall());
	fireDisk = new JoystickButton(driveJoystick, 1);
	fireDisk->WhenPressed(new ShooterShoot());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Teleop Drive", new TeleopDrive());
	SmartDashboard::PutData("Shooter Shoot", new ShooterShoot());
	SmartDashboard::PutData("Shooter Adjust Angle Up", new ShooterAdjustAngleUp());
	SmartDashboard::PutData("Shooter Stop", new ShooterStop());
	SmartDashboard::PutData("Shooter Spin Up", new ShooterSpinUp());
	SmartDashboard::PutData("Drive to Wall", new DrivetoWall());
	SmartDashboard::PutData("Display Sensors", new DisplaySensors());
	SmartDashboard::PutData("Shooter Joystick Drive", new ShooterJoystickDrive());
	SmartDashboard::PutData("Emergency Stop", new EmergencyStop());
	SmartDashboard::PutData("Push Disk", new PushDisk());
	SmartDashboard::PutData("Shooter Adjust Angle Down", new ShooterAdjustAngleDown());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriveJoystick() {
	return driveJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
