// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "PushDisk.h"
PushDisk::PushDisk() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	pusherTimer = new Timer();
}
// Called just before this Command runs the first time
void PushDisk::Initialize() {
	Robot::shooter->feederSpike->Set(Relay::kReverse);
	pusherTimer->Start();
}
// Called repeatedly when this Command is scheduled to run
void PushDisk::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool PushDisk::IsFinished() {
	if(pusherTimer->Get() > 0.5)
		return Robot::shooter->feederSwitch->Get();
	else 
		return false;
}
// Called once after isFinished returns true
void PushDisk::End() {
	Robot::shooter->feederSpike->Set(Relay::kOff);
	pusherTimer->Reset();
	pusherTimer->Stop();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PushDisk::Interrupted() {
	End();
}
